# Email Generator Configuration

# Model Provider Settings
model_provider: "openrouter"  # Options: openai, openrouter

# OpenAI Settings
openai:
  model: "gpt-4-turbo-preview"
  temperature: 0.7
  max_tokens: 2000

# OpenRouter Settings
openrouter:
  base_url: "https://openrouter.ai/api/v1"
  model: "anthropic/claude-3-sonnet"  # Default model
  available_models:
    - "anthropic/claude-3-opus"
    - "anthropic/claude-3-sonnet"
    - "anthropic/claude-3-haiku"
    - "openai/gpt-4-turbo"
    - "openai/gpt-4"
    - "openai/gpt-3.5-turbo"
    - "google/gemini-pro"
    - "meta-llama/llama-3-70b-instruct"
  temperature: 0.7
  max_tokens: 2000
  
# Email Generation Settings
email:
  tone: "professional"  # Options: professional, casual, provocative
  length: "medium"      # Options: short, medium, long
  include_strategy: true
  
# Sequence Settings  
sequence:
  num_emails: 5
  include_breakup: true
  
# Logging
logging:
  level: "INFO"  # Options: DEBUG, INFO, WARNING, ERROR
  file: "email_generator.log"
  
# Output Settings
output:
  format: "text"  # Options: text, html, json
  save_to_file: true
  output_dir: "generated_emails"